package com.agri.ecommerce.ai;

public enum AiChatIntent {
    PRODUCT_SEARCH,
    PRODUCT_DETAIL_HELP,
    CATEGORY_SEARCH,
    CART_HELP,
    CHECKOUT_HELP,
    ORDER_STATUS,
    ORDER_MANAGEMENT,
    PAYMENT_SUPPORT,
    VNPAY_SUPPORT,
    SHIPPING_ADDRESS_HELP,
    DELIVERY_TRACKING,
    DELIVERY_TASK,
    COUPON_SUPPORT,
    REVIEW_SUPPORT,
    CONTACT_SUPPORT,
    ACCOUNT_REGISTER_LOGIN,
    ADMIN_DASHBOARD,
    ADMIN_PRODUCT_MANAGEMENT,
    ADMIN_CATEGORY_MANAGEMENT,
    ADMIN_ORDER_MANAGEMENT,
    ADMIN_PAYMENT_MANAGEMENT,
    ADMIN_COUPON_MANAGEMENT,
    ADMIN_REVIEW_CONTACT_MANAGEMENT,
    GENERAL_SYSTEM_HELP,
    OUT_OF_SCOPE
}
